# Numpy
- Numerical Python
- 산술 계산을 위한 패키지
    - 다차원 배열인 ndarray는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
    - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
    - 선형대수, 난수 생성기, 푸리에 변환 가능
    
- Numpy는 일반적인 산술 데이터 처리를 위한 기본 라이브러리를 제공하기때문에 통계나 분석데이터를 처리하기 위해선 Pandas를 사용해야 한다.
- Numpy가 파이썬 산술 계산 영역에서 중요한 위치를 차지하는 이유중 하나는 대용량 데이터 배열을 효율적으로 다룰수 있도록 설계되어 있다.

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(100000)
my_list = list(range(100000))

In [3]:
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [4]:
my_list #리스트는 값을 넣는 느낌이라 산술연산이 안된다.

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
%time for _ in range(10):my_arr2 = my_arr*2

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 17.6 ms


In [6]:
%time for _ in range(10):my_list2 = [i*2 for i in my_list]

CPU times: user 141 ms, sys: 141 ms, total: 281 ms
Wall time: 351 ms


### Numpy ndarray : 다차원 배열 객체
- Numpy 는 ndarray라고 하는 N차원 배열 객체를 사용한다.
- 배열은 스칼라 원소 간의 연산에서 사용하는 문법과 비슷한 방식을 사용해 전체 데이터 블록에 수학적인 연산을 수행할 수 있도록 해준다.


In [ ]:
# 차원 : 기저 (bae)
# 3차원 : 3개의 기저가 존재
# x축, y축, 시간

# numpy
# 1차원 array = 벡터,1차원 텐서
# 2차원 array = 매트리스, 2차원 텐서
# 3차원 array = 볼륨, 3차원 텐서
# 4차원 이상 array = n차원 텐서



In [8]:
data = np.random.randn(2,3) #2바이 3인 벡터 만듦 차원은 2차원
data

array([[-0.24124655,  0.01954396, -0.23175522],
       [ 0.62547734, -0.95637158, -0.03306024]])

In [10]:
data.ndim #몇 차원인지 알려줌

2

In [11]:
data.shape #몇 바이 몇인지 알 수 있음

(2, 3)

In [12]:
data.size #data가 총 몇개인지?

6

In [33]:
# 1차원,3차원 array를 random하게 만들어 보기
# data.shape이랑 data.ndim 확인


# 나는 randn 뒤에 값이 두개가 필수고, 그 값들 중 앞에 값이 차원이라는 줄 알았는데
# 아니었음. 차원에 따라서 값도 차원 개수만큼 입력해야함

data_1 = np.random.randn(2)  
data_3 = np.random.randn(3,2,1)

In [29]:
data_3

array([[[-1.03176395],
        [ 0.46763285]],

       [[-1.56238851],
        [ 2.24949698]],

       [[-0.2767268 ],
        [ 1.05551208]]])

In [19]:
data_1

array([[-0.53354877, -0.34040526]])

In [30]:
print(data_1.shape)
print(data_3.shape)

(2,)
(3, 2, 1)


In [36]:
data_1.ndim

1

In [37]:
#다른 차원간의 연산도 가능하다. shape이 같아야되나? 암튼 연산 함 갈겨보기
data_3 - data_1

array([[[-0.5551607 , -1.42193031],
        [ 1.60017203,  0.73340242]],

       [[ 0.30446666, -0.56230295],
        [ 0.77598177, -0.09078784]],

       [[ 0.75021958, -0.11655004],
        [-0.40427792, -1.27104754]]])

In [40]:
#객체 type 나타내주기
data_3.dtype

dtype('float64')

### ndarray 생성하기1
- array 함수를 이용해 배열을 생성할 수 있다.

In [41]:
data_4 = [6,7,8,32,2]

In [42]:
type(data_4)

list

In [43]:
arr_1 = np.array(data_4)

In [45]:
arr_1

array([ 6,  7,  8, 32,  2])

In [46]:
data_5 = [[1,2,3,4],  #보통 작성할 때 줄바꿈을 해서 작성한다.
          [2,3,4,5]]

In [47]:
type(data_5)

list

In [49]:
arr_2 = np.array(data_5)
print(type(arr_2))

<class 'numpy.ndarray'>


### ndarray 생성하기2
- np.zeros : 메모리를 초기화 하고 0 으로 채워 넣는다.
- np.empty : zeros와 비슷하지만, 메모리를 초기화 하지 않고 빈값을 넣기 때문에 0 이외의 값이 들어갈수 있다.
- np.ones : 메모리를 초기화 하고 1 로 채워 넣는다.
- np.full : 특정 값으로 채워 넣는다.  
  
- ?????_like : array의 shape 크기만큼 지정된 값으로 채워 array를 반환합니다. 
  
- np. eye : NxN 단위행렬을 생성한다.

In [50]:
# np.zeors((1,2)) or np.zeros([1,2]) 등 과 같이 묶어서 넣어줘야한다.
# 그러니까.. np.zeros(1,2) 이건 안된데이

np.zeros((10,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0.,

In [51]:
np.empty((3,4))

array([[0.5551607 , 1.42193031, 1.60017203, 0.73340242],
       [0.30446666, 0.56230295, 0.77598177, 0.09078784],
       [0.75021958, 0.11655004, 0.40427792, 1.27104754]])

In [54]:
np.full((3,4),4)#객체에 있는 값을 특정값으로 채우는 것? (3,4) array의 값을 4로 채울거얏!

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [58]:
np.eye(7) #단위행렬 생성 단위행렬이란 대각선은 1 나머지는 0

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [60]:
# 요소 곱, 요소들 끼리 곱하기
arr_2 * arr_2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [61]:
# 요소 합, 요소들 끼리 합하기/ 차,나누기 다 가능
arr_2 + arr_2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [63]:
# 요소 간 비교도 가능
arr_2 >= arr_2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [64]:
# 행렬곱
np.dot(arr_2, arr_2.T)

array([[14, 32],
       [32, 77]])

### 데이터 타입
- object.asdtype() : 함수를 통해 dtype을 변경할수 있다.
- 자세한 내용은 공식 문서 참고

### numpy 배열의 산술 연산
- numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할 수 있다.
- 이를 **벡터화** 라고 한다.
- 브로드케스팅과는 다른 개념

In [59]:
arr_2 = np.array([[1,2,3],
                  [4,5,6]])

### 색인과 슬라이싱 기초
- 리스트와 동일하다.

In [65]:
arr_3 = np.arange(10)

In [69]:
arr_3[5:] =12 # 5부터 쭉 12로 바꿔달라!

In [70]:
arr_3

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12, 12])

In [71]:
arr_4= arr_3[1:9]

In [72]:
arr_4[1] = 1234

In [73]:
arr_4

array([   1, 1234,    3,    4,   12,   12,   12,   12])

In [75]:
# numpy에서 오류가 발생한다면, 오류를 함 봐보세요 그러면 문제 해결할 수있는 힌트를 좀 준다.

arr_4[:-1]

array([   1, 1234,    3,    4,   12,   12,   12])

- array에 스칼라 값을 대입하면 영역 전체로 브로드캐스팅 된다.
- list와의 차이점은 배열 조각은 원본 배열의 View이다.즉, 데이터는 복사되지 않고 View에 대한변경은 그대로 원본 배열에 반영 된다.
- View 대신 ndarray의 복사본을 얻고 싶다면 object.copy() 함수를 사용해 명시적으로 배열을 복사해야 한다.

In [77]:
arr_5 = arr_4

In [78]:
id(arr_5)

139808967448112

In [79]:
id(arr_4) #같은 아이디를 쓴다.

139808967448112

In [80]:
arr_4[-1]=10

In [81]:
arr_5 #그래서 arr_4를 바꿔도 arr_5도 바뀐다.

array([   1, 1234,    3,    4,   12,   12,   12,   10])

In [82]:
# 그래서 바뀐 값에 영향을 안받기 위해서 copy를 사용한다.

arr_5 = arr_4.copy()

In [84]:
arr_4[-1] = 12

In [85]:
arr_5

array([   1, 1234,    3,    4,   12,   12,   12,   10])

In [90]:
# array index slicing
arr_6 = np.array([[11,12,13],
                  [21,22,23],
                  [31,32,33],
                  [41,42,43]])

In [91]:
arr_6.shape # 첫번째 [] 안에 4개의 값이 있고, 두번째 []안에는 3개가 있다 라는 뜻

(4, 3)

In [96]:

arr_6[[0,1,2],1]

array([12, 22, 32])

In [97]:
arr_7= np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
])

In [106]:
arr_7

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [114]:
#순서대로 가져온다고 생각하기.
print(arr_7[:, :, 2])

print(arr_7[:, 1, 2]) #shape -> (2,)
print(arr_7[:, [1], [2]]) # shape -> (2,1) 위에랑은 다른 shape 항상 shape을 확인해라


[[ 3  7 11]
 [15 19 23]]
[ 7 19]
[[ 7]
 [19]]


### 블리언 값으로 선택하기
- 중복된 이름이 포함된 배열이 있다고 하자. 그리고 numpy.random 모듈이 있는 randn 함수를 사용해서 임의의 표준 정규분포 데이터를 생성다자.

In [116]:
names = np.array(["오민엽","이성현","박수정","박상민","오민엽","박상민","박상민"])

In [117]:
data = np.random.randn(7,4)

In [120]:
data

array([[-0.07929765,  0.29017938, -0.83668561, -2.3705294 ],
       [-0.53136121, -1.08290352,  1.85255637, -0.59616542],
       [ 1.11328476,  0.41173629,  0.40921915,  1.08092915],
       [ 0.9559586 ,  0.17678513, -0.13116886, -0.21107406],
       [-0.55928138, -1.06620308,  0.38343545, -1.4949455 ],
       [ 0.79126295, -0.22640582,  1.20938192, -0.38350102],
       [ 0.3562021 , -1.92055278, -1.16525039,  1.23688754]])

In [118]:
names == "오민엽" #array([ True, False, False, False,  True, False, False])

array([ True, False, False, False,  True, False, False])

In [123]:
data[data>0.3] #data 값이 0.3보다 큰 애들을 data값을 뽑아오고 싶어.

array([1.85255637, 1.11328476, 0.41173629, 0.40921915, 1.08092915,
       0.9559586 , 0.38343545, 0.79126295, 1.20938192, 0.3562021 ,
       1.23688754])

In [124]:
bool_data = data >0.3

In [125]:
data[bool_data]

array([1.85255637, 1.11328476, 0.41173629, 0.40921915, 1.08092915,
       0.9559586 , 0.38343545, 0.79126295, 1.20938192, 0.3562021 ,
       1.23688754])

In [121]:
data[names=="오민엽"] # 위 True,False 결과값처럼 뽑힌다? 필터링

array([[-0.07929765,  0.29017938, -0.83668561, -2.3705294 ],
       [-0.55928138, -1.06620308,  0.38343545, -1.4949455 ]])

- &(and) 연산, |(or)연산 을 나타낸다. 
- and, or 예약어는 사용할수 없다.

### 팬시 색인
- 정수 배열 색인?

In [126]:
arr_8 = np.empty((8,4))

In [129]:
for i in range(8):
    arr_8[i] = i

In [130]:
arr_8

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정한 row 를 선택하고 싶다면 그냥 원하는 순서가 명시된 정수가 담긴 ndarray 나 list를 넘기면 된다.

In [131]:
arr_8[[4,3,0]] #indexing가능

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [133]:
arr_8[[4,3,0][1]]

array([3., 3., 3., 3.])

In [132]:
arr_8.reshape(16,2)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [3., 3.],
       [3., 3.],
       [4., 4.],
       [4., 4.],
       [5., 5.],
       [5., 5.],
       [6., 6.],
       [6., 6.],
       [7., 7.],
       [7., 7.]])

## 1.6 벡터화 연산 적용하기
- 배열의 여러 원소에 어떤 함수를 적용하고 싶다.
- 함수를 벡터화 시킨후 적용한다.
- vectorize 는 원소를 순회하는 for 루프를 구현한것으로 성능이 좋진 않다. 
- 브로드 캐스팅이 훨신 효율적이다.

In [135]:
mat_1 = np.array(range(1,10)).reshape(3,3)

add_100 = lambda i: i+100

In [138]:
vec_add_100=np.vectorize(add_100)

In [139]:
vec_add_100(mat_1)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [144]:
# 요소를 제곱하고 1을 더하는 함수를 만드신 후에 벡터화를 시켜 array에 적용해 보세요
xx_1 = lambda i: i*i +1
xx_2 = lambda i: i*2 +1

In [146]:
xx_1(mat_1)

array([[ 2,  5, 10],
       [17, 26, 37],
       [50, 65, 82]])

In [148]:
vec_199=np.vectorize(xx_1)

In [150]:
vec_199(mat_1)

array([[ 2,  5, 10],
       [17, 26, 37],
       [50, 65, 82]])

### 배열 전치와 축 바꾸기
- 배열 전치는 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰를 반환하는 기능

In [156]:
arr_t = np.array((1,1,1,1,2))

In [157]:
arr_t.T

array([1, 1, 1, 1, 2])

### 난수를 이용해서 ndarray를 생성하는 방법 - 5가지 존재

- np.random.radint :균일 분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일 분포에서 난수 생성
- np.random.rnadn : 가우시안 표준 정규 분포에서 난수 matrix array 생성

## 유니버설 함수 :배열의 각원소를 빠르게 처리하는 함수
- ufunc 이라고 불리기도 하는 유니버설 함수는 ndarray 안에 있는 데이터 원소별로 연산을 수행하는 함수 이다.
- 유니버설 함수는 하나 이상의 스칼라 값을 받아서 하나 이상의 스칼라 결과값을 반환하는 간단한 함수를 고속으로 수행

### 단항 유니버설 함수
- exp, sqrt

### 이항 유니버설 함수
- maximum
- minimum
- add

이외에 다양한 종류의 함수가 존재함

## 배열지향 프로그래밍
- Numpy 배열을 사용하면 반복문을 작성하지 않고 간결한 배열 연산을 사용해 많은 종류의 데이터 처리 작업을 할 수 있다.
- 배열 연산을 사용해 반복문을 명시적으로 제거하는 기법을 벡터화 라고 한다.

- 위와 동일한 방법으로 반복문을 수행하면 큰 배열을 빠르게 처리 할수 없다.
- 같은 결과를 내는 np.where 함수가 존재 한다.

### 수학 메서드와 통계 메서드
- 합, 평균, 표준편차 를 구할수 있다.

- sum : 배열 전체 혹은 특정 축에 대한 모든 원소의 합을 계산한다. 크기가 0 인 배열에 대한 sum 결과는 0 이다.
- mean : 산술 평균을 구한다. 크기가 0인 배열에 대한 mean 결과는 Nan이다.
- std, var : 각각 표준편차(std)와 분산(var)을 구한다. 선택적으로 자유도를 줄 수 있으며 분모의 기본 값은 n 이다.
- min, max :최솟값과 최댓값
- argmin, argmax : 최소 원소의 색인값과 최대 원소의 색인값
- cumsum : 각 원소의 누적합
- cumprod : 각 원소의 누적곱

### 블리언 배열을 위한 메서드

- any와 all 메서드는 불리언 배열에 유용하다.
- any : 하나 이상의 값이 True 인지 검사
- all : 모든 원소가 True 인지 검사

### 정렬

### 집합 관련함수
- numpy는 1차원 ndarray를 위한 몇 가지 기본적인 집합 연산을 제공한다.
    - unique : 중복된 원소릴 제거한뒤 정렬하여 반환
    - intersec1d : 배열 x와 y에 중복
    - union1d : 두 배열의 합집합
    - setdiff1d :두 배열의 차집합

## 배열 데이터의 파일 입출력
- np.save
- np.load

- 여러개의 배열을 압축된 형태로 저장
    - np.savez
    - np.savez_compressed
    - 두개가 비슷한듯

## 선형대수
- 행렬의 곱셈, 분할, 행렬식에 관한 연산을 알아보자.


### linalg 모듈
- 행렬의 분할과 역행렬, 행렬식과 같은 함수를 포함하고 있다.

- diag : 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나, 1차원 대각선 원소로 하고 나머지는 0으로 채운 단위행렬을 반환한다.
- dot : 행렬 곱셈
- trace : 행렬의 대각선 원소의 합을 계산 한다.
- det : 행렬식을 계산한다.
- eig : 정사각 행렬의 고윳값과 고유 벡터를 계산하다.
- inv : 정사각 행렬의 역행렬을 계산한다.
- qr : QR분해를 계산한다.
- svd : 특잇값 분해(SVD)를 계산한다.
- solve : A가 정사각 행렬일때 Ax = b를 만족하는 x를 구한다.
- lstsq : Ax = b 를 만족하는 최소 제곱해를 구한다. 

http://elearning.kocw.net/contents4/document/lec/2013/Chungbuk/LeeGeonmyeong1/13.pdf

- 점곱 계산

- 행렬 덧셈과 뺄셈

- 행렬 곱셈

- 역행렬
    - 정방행렬의 역행렬 계산

- 행렬의 랭크 구하기

- rank 는 선형 독립적인 행 또는 열의 개수. 특이값 분해를 통해서 계산한다.
- ndim 은 행렬의 차원만을 나타낸다.

- 행렬식 계산하기

- 행렬의 대각 원소 추출하기

# 고급 Numpy

## ndarray배열 재형성 하기
- 배열의 모양을 변환하려면 배열의 인스턴스 메서드인 reshape 메서드에 새로운 모양을 나타내는 튜플을 넘기면 된다.

- reshape 에 넘기는 값 중 하나가 -1이 될 수도 있는데 이경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 된다.
- -1은 가능한 많이라는 의미로 사용된다. 
- magic keyword 

- 다차원 배열을 낮은 차원으로 변환하는 것은 **평탄화** 라고 한다.

# 배열 이어붙이고 나누기

### 브로드캐스팅
- 브로드캐스팅은 다른 모양의 배열 간의 산술 연산을 어떻게 수행해야 하는지 설명한다.

- 여기서 스칼라 값 4는 곱셈 연산 과정에서 배열의 모든 원소로 브로드캐스트 되었다.

#### 브로드캐스팅 규칙
- 각차원에 대해 축의 길이가 일치하거나 둘 중 하나의 길이가 1이라면 두 배열은 브로드 캐스팅 호환이다. 