In [1]:
import numpy as np

## 선형대수
- 행렬의 곱셈, 분할, 행렬식에 관한 연산을 알아보자.


In [ ]:
x = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
y = np.array([[6,20],
             [7,21],
             [8,22]])

In [ ]:
np.dot(x,y) #행렬곱 

array([[ 44, 128],
       [107, 317]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [ ]:
z = np.array([[1],
         [1],
         [1]])

In [ ]:
np.dot(x,z).shape

(2, 1)

In [ ]:
x @ z

array([[ 6],
       [15]])

In [ ]:
x @ np.ones(3)

array([ 6., 15.])

### linalg 모듈
- 행렬의 분할과 역행렬, 행렬식과 같은 함수를 포함하고 있다.

- diag : 정사각 행렬의 대각/비대각 원소를 1차원 배열로 반환하거나, 1차원 대각선 원소로 하고 나머지는 0으로 채운 단위행렬을 반환한다.
- dot : 행렬 곱셈
- trace : 행렬의 대각선 원소의 합을 계산 한다.
- det : 행렬식을 계산한다.
- eig : 정사각 행렬의 고윳값과 고유 벡터를 계산하다.
- inv : 정사각 행렬의 역행렬을 계산한다.
- qr : QR분해를 계산한다.
- svd : 특잇값 분해(SVD)를 계산한다.
- solve : A가 정사각 행렬일때 Ax = b를 만족하는 x를 구한다.
- lstsq : Ax = b 를 만족하는 최소 제곱해를 구한다.

http://elearning.kocw.net/contents4/document/lec/2013/Chungbuk/LeeGeonmyeong1/13.pdf

- 점곱 계산

In [ ]:
# 두 벡터를 만듭니다.
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# 점곱을 계산합니다.
np.dot(vector_a, vector_b)

32

In [ ]:
scalar_a = np.array(1)
scalar_b = np.array(2)
np.dot(scalar_a, scalar_b)

2

In [ ]:
# 스칼라 배열에서는 적용되지 않는다.
#스칼라는 벡터보다 작은 것
scalar_a @ scalar_b

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

- 행렬 덧셈과 뺄셈

In [ ]:
# 행렬을 만듭니다.
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# 행렬을 만듭니다.
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# 두 행렬을 더합니다.
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
# 두 행렬을 뺍니다.
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
# 두 행렬을 더합니다.
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

- 행렬 곱셈

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
matrix_a = np.array([[1, 1],
                     [1, 2]])

# 행렬을 만듭니다.
matrix_b = np.array([[1, 3],
                     [1, 2]])

# 두 행렬을 곱합니다.
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [ ]:
# 두 행렬을 곱합니다.
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [ ]:
# 두 행렬의 원소별 곱셈을 수행합니다.
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

- 역행렬
    - 정방행렬의 역행렬 계산

In [ ]:
matrix = np.array([[1, 4],
                   [2, 5]])

# 역행렬을 계산합니다.
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [ ]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [ ]:
matrix = np.array([[1, 4, 7],
                   [2, 5, 8]])

# 유사 역행렬을 계산합니다.
np.linalg.pinv(matrix)

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

- 행렬의 랭크 구하기

In [ ]:
# 라이브러리를 임포트합니다.
import numpy as np

# 행렬을 만듭니다.
mat_1 = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# 행렬의 랭크를 반환합니다.
np.linalg.matrix_rank(mat_1)

2

In [ ]:
mat_2 = np.array([[1, 1, 1],
                   [1, 1, 1],
                   [1, 1, 1]])


In [ ]:
np.linalg.matrix_rank(mat_2)

1

- rank 는 선형 독립적인 행 또는 열의 개수. 특이값 분해를 통해서 계산한다.
- ndim 은 행렬의 차원만을 나타낸다.

넘파이 0.18 버전에서 `rank()` 함수가 삭제되었습니다. 대신 `ndim()` 함수를 사용하세요.

In [ ]:
# 2D 배열이므로 2가 반환됩니다.
np.ndim(mat_2)

2

- 행렬식 계산하기

In [ ]:
# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# 행렬의 행렬식을 반환합니다.
np.linalg.det(matrix)

0.0

- 행렬의 대각 원소 추출하기

In [ ]:
matrix.diagonal()

array([1, 4, 9])

- 행렬의 대각합 계싼

In [ ]:
matrix.trace()

14

In [ ]:
sum(matrix.diagonal())

14

In [ ]:
# 행렬을 만듭니다.
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# 고윳값과 고유벡터를 계산합니다.
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# 고윳값을 확인합니다.
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [ ]:
# 고유벡터를 확인합니다.
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [ ]:
# 추가
# 대칭 행렬을 만듭니다.
matrix = np.array([[1, -1, 3],
                   [-1, 1, 6],
                   [3, 6, 9]])

# 고윳값과 고유벡터를 계산합니다.
eigenvalues, eigenvectors = np.linalg.eigh(matrix)

# 고급 Numpy

## ndarray배열 재형성 하기
- 배열의 모양을 변환하려면 배열의 인스턴스 메서드인 reshape 메서드에 새로운 모양을 나타내는 튜플을 넘기면 된다.

### C 순서와 포트란 순서
- 기본적으로 NumPy 배열은 **로우 우선**순서로 생성된다. 이말은 만약 2차원 배열이 있다면 배열의 각 로우에 해당하는 데이터들은 공간적으로 인접한 메모리에 적재된다는 뜻이다.
- C (로우우선 순서) : 상위 차원을 우선 탐색 한다.(1번 축을 0번 축보다 우선 탐색한다.)
- 포트란 (컬럼 우선 순서) : 사우이 차원을 나중에 탐색한다.(0번 축을 1번 축보다 우선 탐색한다.)

In [ ]:
arr = np.arange(8)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

- reshape 의 order 의 값에 따라 재형성 순서가 결정된다.
    - order ='C': 로우 우서(C순서)
    - order ='F': 컬럼 우선(포트란순서)

In [ ]:
arr.reshape((4,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr.reshape((4,2), order='F')

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

- reshape 에 넘기는 값 중 하나가 -1이 될 수도 있는데 이경우에는 원본 데이터를 참조해서 적절한 값을 추론하게 된다.
- -1은 가능한 많이라는 의미로 사용된다.
- magic keyword

In [ ]:
arr = np.arange(15)

In [ ]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
arr = np.arange(30)

In [ ]:
arr_1 = arr.reshape((5,2,-1))

In [ ]:
arr_1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

- 다차원 배열을 낮은 차원으로 변환하는 것은 **평탄화** 라고 한다.

In [ ]:
arr_1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [ ]:
arr_1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr_1.ravel('F')

array([ 0,  6, 12, 18, 24,  3,  9, 15, 21, 27,  1,  7, 13, 19, 25,  4, 10,
       16, 22, 28,  2,  8, 14, 20, 26,  5, 11, 17, 23, 29])

In [ ]:
arr_1.reshape((-1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr_1.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# 배열 이어붙이고 나누기

In [ ]:
arr1 = np.array(([11,12,13],
              [14,15,16]))
arr2 = np.array(([21,22,23],
              [24,25,26]))

In [ ]:
np.concatenate([arr1,arr2],axis=0)

array([[11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate([arr1,arr2],axis=1)

array([[11, 12, 13, 21, 22, 23],
       [14, 15, 16, 24, 25, 26]])

In [ ]:
# 실제로 어떻게 동작하는지 확인해 봐야하릇
np.split(arr1,[1,3])

[array([[11, 12, 13]]),
 array([[14, 15, 16]]),
 array([], shape=(0, 3), dtype=int32)]

### 브로드캐스팅
- 브로드캐스팅은 다른 모양의 배열 간의 산술 연산을 어떻게 수행해야 하는지 설명한다.

In [ ]:
arr_1 = np.arange(5)

In [ ]:
arr_1

array([0, 1, 2, 3, 4])

In [ ]:
arr_1*4

array([ 0,  4,  8, 12, 16])

- 여기서 스칼라 값 4는 곱셈 연산 과정에서 배열의 모든 원소로 브로드캐스트 되었다.

In [ ]:
arr_1.mean(0)

2.0

In [ ]:
arr_2 = np.random.randn(4,3)

In [ ]:
arr_2

array([[-2.6950185 , -1.01377031,  0.48165881],
       [ 0.98812862, -1.2449303 ,  0.5260334 ],
       [-0.08359242, -0.22553094, -1.29938486],
       [ 0.82813041, -2.03703304,  1.02251274]])

In [ ]:
arr_2.mean(0)

array([-0.24058797, -1.13031615,  0.18270502])

In [ ]:
arr_2.mean(1)

array([-1.07571   ,  0.08974391, -0.5361694 , -0.06212996])

#### 브로드캐스팅 규칙
- 각차원에 대해 축의 길이가 일치하거나 둘 중 하나의 길이가 1이라면 두 배열은 브로드 캐스팅 호환이다.

In [ ]:
arr_1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

In [ ]:
arr_2 = np.array([1,2,3])

In [ ]:
arr_1 + arr_2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
arr_3 = np.array([[1],[2],[3],[4]])

In [ ]:
arr_1 + arr_3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [ ]:
arr_1.shape

(4, 3)

In [ ]:
arr_2.shape

(3,)

In [ ]:
arr_3.shape

(4, 1)

In [ ]:
arr_3d_1 = np.random.rand(3,4,2)

In [ ]:
arr_3d_2 = np.random.rand(4,2)

In [ ]:
arr_3d_3 = np.random.rand(3,4)

In [ ]:
(arr_3d_1 + arr_3d_2).shape

(3, 4, 2)